// Footprints — single-projection composite map with a GPU-composited camera.
//
// Map: assets/maps/world-composite.svg, generated by scripts/build-map.mjs.
// All layers (countries + CN/US admin-1) share ONE Natural Earth 1
// projection, so detail borders align with the world layer at any zoom.
//
// Camera: pan/zoom is a single CSS transform (translate + scale) on the
// .fp-cam wrapper — GPU-composited, will-change: transform. Wheel/pinch
// zoom anchors at the pointer; discrete steps glide via ~140ms ease-out
// rAF interpolation. During pan/zoom the ONLY per-frame DOM write is that
// transform; threshold checks run at most once per rAF tick and toggle
// classes only when state changes (all nodes are prebuilt).
//
// Semantic zoom: past DETAIL_ZOOM the CN/US country fills crossfade to
// their admin-1 groups; past CITY_ZOOM labeled dots appear for regions
// with lat/lng (projected at build/runtime with the identical formula).
// Clicking a visited country animates zoom-to-fit; ocean click or reset
// animates back to the world view. No modal.
(function () {
  "use strict";

  var section = document.getElementById("footprints");
  var host = document.getElementById("fp-map");
  var cam = document.getElementById("fp-cam");
  var tip = document.getElementById("fp-tip");
  if (!section || !host || !cam || !tip || typeof FOOTPRINTS === "undefined") return;

  var MIN_ZOOM = 1;
  var MAX_ZOOM = 8;
  var DETAIL_ZOOM = 2.5;
  var CITY_ZOOM = 4;
  var DETAIL_COUNTRIES = ["CN", "US"]; // admin-1 groups present in the SVG

  function slug(name) {
    return name.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  }

  // ---- Camera state ------------------------------------------------------
  var svg = null;
  var W = 0, H = 0;          // host px size
  var cur = { s: 1, x: 0, y: 0 };     // rendered state
  var target = { s: 1, x: 0, y: 0 };  // target state (wheel steps retarget)
  var anim = null;           // {from, to, t0, dur}
  var rafId = null;
  var strokeBucket = -1;
  var zoomedFlags = { detail: false, cities: false };

  function clampT(t, s) {
    t.x = Math.min(0, Math.max(W - W * s, t.x));
    t.y = Math.min(0, Math.max(H - H * s, t.y));
    return t;
  }

  function apply() {
    cam.style.transform =
      "translate(" + cur.x + "px," + cur.y + "px) scale(" + cur.s + ")";
  }

  // occasional (bucketed) writes — NOT per-frame: crossfade thresholds and
  // stroke-width compensation so borders stay hairline while zoomed
  function thresholds() {
    var wantDetail = cur.s >= DETAIL_ZOOM;
    var wantCities = cur.s >= CITY_ZOOM;
    if (wantDetail !== zoomedFlags.detail) {
      zoomedFlags.detail = wantDetail;
      svg.classList.toggle("fp-zoomed", wantDetail);
    }
    if (wantCities !== zoomedFlags.cities) {
      zoomedFlags.cities = wantCities;
      svg.classList.toggle("fp-cities-on", wantCities);
    }
    var bucket = Math.round(cur.s * 4);
    if (bucket !== strokeBucket) {
      strokeBucket = bucket;
      cam.style.setProperty("--fp-sw", (0.5 / cur.s).toFixed(3));
      cam.style.setProperty("--fp-inv", (1 / cur.s).toFixed(4));
    }
  }

  function easeOut(t) { return 1 - Math.pow(1 - t, 3); }

  function frame(now) {
    rafId = null;
    if (anim) {
      var t = Math.min(1, (now - anim.t0) / anim.dur);
      var e = easeOut(t);
      cur.s = anim.from.s + (anim.to.s - anim.from.s) * e;
      cur.x = anim.from.x + (anim.to.x - anim.from.x) * e;
      cur.y = anim.from.y + (anim.to.y - anim.from.y) * e;
      if (t >= 1) anim = null;
    }
    apply();        // the one per-frame DOM write
    thresholds();   // class toggles only on change
    if (anim) schedule();
  }

  function schedule() {
    if (rafId === null) rafId = requestAnimationFrame(frame);
  }

  function animateTo(s, x, y, dur) {
    var to = clampT({ x: x, y: y }, s);
    target = { s: s, x: to.x, y: to.y };
    anim = { from: { s: cur.s, x: cur.x, y: cur.y }, to: target, t0: performance.now(), dur: dur || 140 };
    schedule();
  }

  function setDirect(s, x, y) {
    anim = null;
    var t = clampT({ x: x, y: y }, s);
    target = { s: s, x: t.x, y: t.y };
    cur = { s: s, x: t.x, y: t.y };
    schedule();
  }

  // zoom by factor anchored at host-relative point (px, py); animated
  function zoomAt(px, py, factor, dur) {
    var s2 = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, target.s * factor));
    var ratio = s2 / target.s;
    var x2 = px - (px - target.x) * ratio;
    var y2 = py - (py - target.y) * ratio;
    animateTo(s2, x2, y2, dur);
  }

  function resetView(dur) {
    animateTo(1, 0, 0, dur || 300);
  }

  // ---- Projection (identical to the build; constants from the SVG) -------
  var proj = null;

  function makeProjection() {
    var k = parseFloat(svg.dataset.projK);
    var tx = parseFloat(svg.dataset.projTx);
    var ty = parseFloat(svg.dataset.projTy);
    return function (lat, lng) {
      var l = lng * Math.PI / 180, p = lat * Math.PI / 180;
      var p2 = p * p, p4 = p2 * p2;
      var x = l * (0.8707 - 0.131979 * p2 + p4 * (-0.013791 + p4 * (0.003971 * p2 - 0.001529 * p4)));
      var y = p * (1.007226 + p2 * (0.015085 + p4 * (-0.044475 + 0.028874 * p2 - 0.005916 * p4)));
      return { x: tx + k * x, y: ty - k * y };
    };
  }

  // ---- Build-once decorations -------------------------------------------
  var regionMeta = {}; // "r-CC-slug" -> { date }
  var bboxCache = {};

  function decorate() {
    Object.keys(FOOTPRINTS).forEach(function (code) {
      var d = FOOTPRINTS[code];
      if (!d.visited) return;
      var p = svg.querySelector('[id="c-' + code + '"]');
      if (p) p.classList.add("visited");
      (d.regions || []).forEach(function (rg) {
        var id = "r-" + code + "-" + slug(rg.name);
        var rp = svg.querySelector('[id="' + id + '"]');
        if (rp) {
          rp.classList.add("visited");
          regionMeta[id] = { date: rg.date || "" };
        }
      });
    });

    // un-hide admin-1 groups: visibility is class-driven (opacity) from here
    DETAIL_COUNTRIES.forEach(function (cc) {
      var g = svg.querySelector("#admin1-" + cc);
      if (g) g.removeAttribute("hidden");
    });

    // city dots (regions with lat/lng only — positions never guessed)
    var cities = document.createElementNS("http://www.w3.org/2000/svg", "g");
    cities.setAttribute("class", "fp-cities");
    Object.keys(FOOTPRINTS).forEach(function (code) {
      (FOOTPRINTS[code].regions || []).forEach(function (rg) {
        if (!FOOTPRINTS[code].visited) return;
        if (typeof rg.lat !== "number" || typeof rg.lng !== "number") return;
        var pt = proj(rg.lat, rg.lng);
        var g = document.createElementNS("http://www.w3.org/2000/svg", "g");
        g.setAttribute("class", "fp-city");
        g.setAttribute("transform", "translate(" + pt.x.toFixed(1) + " " + pt.y.toFixed(1) + ")");
        var dot = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        dot.setAttribute("r", "1.4");
        var label = document.createElementNS("http://www.w3.org/2000/svg", "text");
        // vertical offset comes from CSS (counter-scaled with zoom)
        label.textContent = rg.name;
        g.appendChild(dot);
        g.appendChild(label);
        cities.appendChild(g);
      });
    });
    svg.appendChild(cities);
  }

  // ---- Interaction -------------------------------------------------------
  function hostPoint(e) {
    var r = host.getBoundingClientRect();
    return { x: e.clientX - r.left, y: e.clientY - r.top };
  }

  function countryOf(p) {
    if (p.id && p.id.slice(0, 2) === "c-") return p.id.slice(2);
    var g = p.closest("g[id^='admin1-']");
    if (g) return g.id.slice(7);
    return null;
  }

  function zoomToCountry(code) {
    var p = svg.querySelector('[id="c-' + code + '"]');
    if (!p) return;
    var bb = bboxCache[code] || (bboxCache[code] = p.getBBox());
    var vb = svg.viewBox.baseVal;
    var ppu = W / vb.width; // px per svg unit
    var s = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM,
      0.85 * Math.min(vb.width / bb.width, vb.height / bb.height)));
    var cx = (bb.x + bb.width / 2) * ppu;
    var cy = (bb.y + bb.height / 2) * ppu;
    animateTo(s, W / 2 - cx * s, H / 2 - cy * s, 420);
  }

  function bind() {
    // wheel zoom, anchored at pointer, animated
    host.addEventListener("wheel", function (e) {
      e.preventDefault();
      var pt = hostPoint(e);
      zoomAt(pt.x, pt.y, Math.exp(-e.deltaY * 0.0022), 140);
    }, { passive: false });

    // drag pan (mouse)
    var dragging = false, moved = false, sx = 0, sy = 0, ox = 0, oy = 0;
    host.addEventListener("mousedown", function (e) {
      dragging = true;
      moved = false;
      sx = e.clientX; sy = e.clientY;
      ox = target.x; oy = target.y;
    });
    window.addEventListener("mousemove", function (e) {
      if (!dragging) return;
      var dx = e.clientX - sx, dy = e.clientY - sy;
      if (Math.abs(dx) + Math.abs(dy) > 3) moved = true;
      setDirect(target.s, ox + dx, oy + dy);
    });
    window.addEventListener("mouseup", function () { dragging = false; });

    // two-finger pinch/pan (one finger stays free for page scroll)
    var pinchDist = 0, pinchZoom = 1, pinchMid = null;
    host.addEventListener("touchstart", function (e) {
      if (e.touches.length !== 2) return;
      e.preventDefault();
      pinchDist = Math.hypot(e.touches[0].clientX - e.touches[1].clientX,
                             e.touches[0].clientY - e.touches[1].clientY);
      pinchZoom = target.s;
      var r = host.getBoundingClientRect();
      pinchMid = { x: (e.touches[0].clientX + e.touches[1].clientX) / 2 - r.left,
                   y: (e.touches[0].clientY + e.touches[1].clientY) / 2 - r.top };
    }, { passive: false });
    host.addEventListener("touchmove", function (e) {
      if (e.touches.length !== 2 || !pinchMid) return;
      e.preventDefault();
      var r = host.getBoundingClientRect();
      var m = { x: (e.touches[0].clientX + e.touches[1].clientX) / 2 - r.left,
                y: (e.touches[0].clientY + e.touches[1].clientY) / 2 - r.top };
      var dist = Math.hypot(e.touches[0].clientX - e.touches[1].clientX,
                            e.touches[0].clientY - e.touches[1].clientY);
      var s2 = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, pinchZoom * dist / pinchDist));
      var ratio = s2 / target.s;
      var x2 = pinchMid.x - (pinchMid.x - target.x) * ratio + (m.x - pinchMid.x);
      var y2 = pinchMid.y - (pinchMid.y - target.y) * ratio + (m.y - pinchMid.y);
      pinchMid = m;
      setDirect(s2, x2, y2);
    }, { passive: false });
    host.addEventListener("touchend", function () { pinchMid = null; });

    // double-click zoom
    host.addEventListener("dblclick", function (e) {
      e.preventDefault();
      var pt = hostPoint(e);
      zoomAt(pt.x, pt.y, 1.9, 200);
    });

    // click: visited country → zoom to fit; ocean → back to world view
    svg.addEventListener("click", function (e) {
      if (moved) return; // it was a drag
      var p = e.target.closest("path");
      if (!p) {
        if (cur.s > 1.05) resetView();
        return;
      }
      var code = countryOf(p);
      if (code && FOOTPRINTS[code] && FOOTPRINTS[code].visited) {
        zoomToCountry(code);
      } else if (cur.s > 1.05 && !code) {
        resetView();
      }
    });
    host.addEventListener("click", function (e) {
      if (!moved && e.target === host) {
        if (cur.s > 1.05) resetView();
      }
    });

    // hover tooltip: country name, or region name + date when zoomed in
    svg.addEventListener("mouseover", function (e) {
      var p = e.target.closest("path");
      if (!p) { tip.hidden = true; return; }
      var g = p.closest("g[id^='admin1-']");
      if (g) {
        var meta = regionMeta[p.id];
        var rn = p.getAttribute("name") || "";
        tip.textContent = meta && meta.date ? rn + " · " + meta.date : rn;
        tip.classList.toggle("muted", !p.classList.contains("visited"));
        tip.hidden = false;
        return;
      }
      var code = p.id.slice(2);
      var d = FOOTPRINTS[code];
      var name = p.getAttribute("name") || (d && d.name) || "";
      if (d && d.visited) {
        var n = (d.regions || []).length;
        tip.textContent = name + " · " + n + (n === 1 ? " region" : " regions");
        tip.classList.remove("muted");
      } else {
        tip.textContent = name;
        tip.classList.add("muted");
      }
      tip.hidden = false;
    });
    svg.addEventListener("mouseleave", function () { tip.hidden = true; });
    svg.addEventListener("mousemove", function (e) {
      var pt = hostPoint(e);
      tip.style.transform = "translate(" + (pt.x + 14) + "px," + (pt.y + 14) + "px)";
    }, { passive: true });

    // controls
    var box = document.createElement("div");
    box.className = "fp-zoom-controls";
    [["+", "Zoom in", function () { zoomAt(W / 2, H / 2, 1.6, 180); }],
     ["−", "Zoom out", function () { zoomAt(W / 2, H / 2, 1 / 1.6, 180); }],
     ["⟲", "Reset view", function () { resetView(); }]].forEach(function (def) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = "fp-zoom-btn";
      b.textContent = def[0];
      b.setAttribute("aria-label", def[1]);
      b.title = def[1];
      b.addEventListener("click", def[2]);
      box.appendChild(b);
    });
    host.parentNode.appendChild(box);

    // keep camera valid on resize
    var rt = null;
    window.addEventListener("resize", function () {
      clearTimeout(rt);
      rt = setTimeout(function () {
        W = host.clientWidth;
        H = host.clientHeight;
        setDirect(target.s, target.x, target.y);
      }, 150);
    });
  }

  // ---- Stat rings --------------------------------------------------------
  function initRings() {
    var CIRC = 2 * Math.PI * 30;
    var reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    var countries = Object.keys(FOOTPRINTS).filter(function (k) {
      return FOOTPRINTS[k].visited;
    }).length;
    var states = ((FOOTPRINTS.US || {}).regions || []).length;

    var defs = [
      { fill: "ring-countries", num: "ring-countries-num", value: countries, total: 195 },
      { fill: "ring-states", num: "ring-states-num", value: states, total: 50 },
    ];
    defs.forEach(function (d) {
      var el = document.getElementById(d.fill);
      var num = document.getElementById(d.num);
      if (!el || !num) return;
      num.textContent = String(d.value);
      el.style.strokeDasharray = String(CIRC);
      el.style.strokeDashoffset = String(CIRC);
      d.offset = CIRC * (1 - Math.min(1, d.value / d.total));
    });

    function fill() {
      defs.forEach(function (d) {
        var el = document.getElementById(d.fill);
        if (el) el.style.strokeDashoffset = String(d.offset);
      });
    }

    if (reduced || !("IntersectionObserver" in window)) {
      fill();
      return;
    }
    var rio = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) {
          rio.disconnect();
          requestAnimationFrame(fill); // arc animates via CSS transition
        }
      });
    }, { threshold: 0.4 });
    rio.observe(document.getElementById("fp-rings"));
  }

  // ---- Init --------------------------------------------------------------
  var inited = false;

  function init() {
    if (inited) return;
    inited = true;
    initRings();
    fetch("assets/maps/world-composite.svg")
      .then(function (r) { return r.text(); })
      .then(function (txt) {
        cam.innerHTML = txt;
        svg = cam.querySelector("svg");
        if (!svg) return;
        W = host.clientWidth;
        H = host.clientHeight;
        proj = makeProjection();
        decorate();
        bind();
        apply();
        thresholds();
      })
      .catch(function () {
        cam.innerHTML = "<p class='archive-sub'>Couldn't load the map.</p>";
      });
  }

  if ("IntersectionObserver" in window) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) {
          io.disconnect();
          init();
        }
      });
    }, { rootMargin: "400px" });
    io.observe(section);
  } else {
    init();
  }
})();
