#!/usr/bin/env node
// Photo build pipeline.
//
// Input:  photos-original/<Category>/<name>.(jpg|jpeg|png|heic)
//         (git-ignored — originals are never committed)
// Output: assets/photos/<category>/<name>.webp        (long edge 1600, q80)
//         assets/photos/thumbs/<category>/<name>.webp (long edge 400)
//         js/data/photos.js regenerated from the outputs.
//
// Manual edits to caption/date in js/data/photos.js are PRESERVED across
// regenerations (merged by id). HEIC input requires a sharp build with
// libheif; if yours lacks it, convert HEIC to JPG first.
//
// Usage: npm run photos

import { readdir, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SRC_DIR = "photos-original";
const OUT_DIR = "assets/photos";
const THUMB_DIR = "assets/photos/thumbs";
const MANIFEST = "js/data/photos.js";
const EXTS = new Set([".jpg", ".jpeg", ".png", ".heic"]);

function prettify(name) {
  return name.replace(/[-_]+/g, " ").replace(/\s+/g, " ").trim();
}

async function existingById() {
  const map = new Map();
  if (!existsSync(MANIFEST)) return map;
  const src = await readFile(MANIFEST, "utf8");
  try {
    const photos = new Function(`${src}; return PHOTOS;`)();
    for (const p of photos) if (p.id) map.set(p.id, p);
  } catch {
    console.warn("warn: could not parse existing manifest; starting fresh");
  }
  return map;
}

async function main() {
  if (!existsSync(SRC_DIR)) {
    console.error(`No ${SRC_DIR}/ directory found. Create it, add ` +
      `<Category>/<name>.jpg files, then re-run.`);
    process.exit(1);
  }

  const prior = await existingById();
  const entries = [];

  const categories = (await readdir(SRC_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  for (const cat of categories) {
    const catSlug = cat.toLowerCase();
    const catLabel = cat.charAt(0).toUpperCase() + cat.slice(1);
    const outCat = path.join(OUT_DIR, catSlug);
    const thumbCat = path.join(THUMB_DIR, catSlug);
    await mkdir(outCat, { recursive: true });
    await mkdir(thumbCat, { recursive: true });

    const files = (await readdir(path.join(SRC_DIR, cat)))
      .filter((f) => EXTS.has(path.extname(f).toLowerCase()))
      .sort();

    for (const file of files) {
      const base = path.basename(file, path.extname(file)).toLowerCase();
      const id = `${catSlug}-${base}`;
      const srcFile = path.join(SRC_DIR, cat, file);
      const webPath = path.join(outCat, `${base}.webp`);
      const thumbPath = path.join(thumbCat, `${base}.webp`);

      const image = sharp(srcFile, { failOn: "none" }).rotate();
      const full = await image
        .clone()
        .resize(1600, 1600, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: 80 })
        .toFile(webPath);
      await image
        .clone()
        .resize(400, 400, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(thumbPath);

      const old = prior.get(id) || {};
      entries.push({
        id,
        src: webPath.split(path.sep).join("/"),
        thumb: thumbPath.split(path.sep).join("/"),
        category: catLabel,
        // manual edits survive regeneration:
        caption: old.caption || prettify(base),
        date: old.date || "",
        w: full.width,
        h: full.height,
      });
      console.log(`✓ ${id}  (${full.width}×${full.height})`);
    }
  }

  const header = `// ============================================================
// Photography manifest — GENERATED by scripts/build-photos.mjs.
//
// To add a photo: drop the original into photos-original/<Category>/
// and run \`npm run photos\` (see README "Adding photos").
// You MAY hand-edit \`caption\` and \`date\` here — those two fields are
// preserved the next time the generator runs (merged by id). Other
// fields are overwritten.
// ============================================================

const PHOTOS = `;

  const body = JSON.stringify(entries, null, 2)
    .replace(/"([a-zA-Z_][a-zA-Z0-9_]*)":/g, "$1:");
  await writeFile(MANIFEST, header + body + ";\n");
  console.log(`\nWrote ${entries.length} entries to ${MANIFEST}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
